# Generated by Django 5.2.5 on 2025-08-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
